services:
  server:
    image: node:22-alpine
    container_name: movie_backend
    volumes:
      - ./:/movie_app
    env_file:
      - .env
    working_dir: /movie_app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 7000:5000
    depends_on:
      - database

  database: 
    image: postgres:16-alpine
    container_name: for-postgres
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432